#!/bin/bash
# Quick Start Guide for Notification Module
# Run these commands in order to set up and test the notification system

echo "=========================================="
echo "Smart Campus Operations Hub"
echo "Notification Module - Quick Start Guide"
echo "=========================================="
echo ""

# Step 1: Backend Setup
echo "STEP 1: Building Backend..."
echo "cd backend"
echo "./mvnw clean install"
echo ""

# Step 2: Run Backend
echo "STEP 2: Starting Backend Server..."
echo "./mvnw spring-boot:run"
echo "✓ Backend will be running on http://localhost:8081"
echo ""

# Step 3: Frontend Setup
echo "STEP 3: Setting Up Frontend..."
echo "cd ../frontend"
echo "npm install"
echo ""

# Step 4: Run Frontend
echo "STEP 4: Starting Frontend Server..."
echo "npm run dev"
echo "✓ Frontend will be running on http://localhost:5173"
echo ""

echo "=========================================="
echo "NEXT STEPS"
echo "=========================================="
echo ""

echo "1. Login to the application"
echo "   - Navigate to http://localhost:5173/login"
echo "   - Use your credentials or create a test account"
echo ""

echo "2. View Notification Panel"
echo "   - Click the bell icon in the navbar"
echo "   - Should show 'No notifications' initially"
echo ""

echo "3. Create a Booking (if Module B is ready)"
echo "   - Go to Facilities and create a booking"
echo "   - Admin approves it"
echo "   - Check notification bell for approval notification"
echo ""

echo "4. Check Notification History"
echo "   - Visit http://localhost:5173/notifications"
echo "   - Should show all your notifications"
echo "   - Filter by category (Booking, Ticket, System)"
echo ""

echo "5. Customize Notification Preferences"
echo "   - Visit http://localhost:5173/notification-preferences"
echo "   - Toggle different notification types"
echo "   - Save preferences"
echo ""

echo "6. Test API Endpoints (Postman)"
echo "   - Import endpoints from NOTIFICATION_API_DOCUMENTATION.md"
echo "   - Test each endpoint"
echo "   - GET /api/notifications/{userId}"
echo "   - PUT /api/notifications/{id}/mark-as-read"
echo "   - POST /api/notifications/preferences/{userId}"
echo ""

echo "=========================================="
echo "API ENDPOINTS SUMMARY"
echo "=========================================="
echo ""
echo "Base URL: http://localhost:8081/api/notifications"
echo ""
echo "GET    /api/notifications/{userId}                           (Paginated list)"
echo "GET    /api/notifications/{userId}/count                     (Unread count)"
echo "GET    /api/notifications/{userId}/unread                    (Unread only)"
echo "GET    /api/notifications/{userId}/category/{category}       (Filter by type)"
echo "GET    /api/notifications/detail/{id}                        (Single notification)"
echo "GET    /api/notifications/preferences/{userId}               (User preferences)"
echo ""
echo "PUT    /api/notifications/{id}/mark-as-read                  (Mark read)"
echo "PUT    /api/notifications/{id}/mark-as-unread                (Mark unread)"
echo "PUT    /api/notifications/{userId}/mark-all-as-read          (Mark all read)"
echo ""
echo "DELETE /api/notifications/{id}                               (Delete notification)"
echo ""
echo "POST   /api/notifications/preferences/{userId}               (Save preferences)"
echo ""

echo "=========================================="
echo "ENVIRONMENT SETUP (Optional - for email)"
echo "=========================================="
echo ""
echo "Set these environment variables for email notifications:"
echo "export MAIL_HOST=smtp.gmail.com"
echo "export MAIL_PORT=587"
echo "export MAIL_USERNAME=your-email@gmail.com"
echo "export MAIL_PASSWORD=your-app-specific-password"
echo ""
echo "Note: For Gmail, create an App Password at:"
echo "https://myaccount.google.com/apppasswords"
echo ""

echo "=========================================="
echo "TESTING CHECKLIST"
echo "=========================================="
echo ""
echo "□ Can see notification bell in navbar"
echo "□ Notification bell shows unread count badge"
echo "□ Can open notification panel"
echo "□ Can mark notifications as read"
echo "□ Can delete notifications"
echo "□ Can visit /notifications page"
echo "□ Can filter by category"
echo "□ Can visit /notification-preferences"
echo "□ Can toggle notification settings"
echo "□ API endpoints work in Postman"
echo "□ Notifications trigger on booking approval"
echo "□ Notifications trigger on ticket creation"
echo "□ Email notifications send (if configured)"
echo ""

echo "=========================================="
echo "TROUBLESHOOTING"
echo "=========================================="
echo ""
echo "Issue: Notifications not showing"
echo "Fix: Check if user is logged in and userId is stored"
echo ""
echo "Issue: API returns 404"
echo "Fix: Verify MongoDB is running and connected"
echo ""
echo "Issue: Frontend not updating notifications"
echo "Fix: Clear browser cache and refresh"
echo ""
echo "Issue: Email not sending"
echo "Fix: Check email configuration in environment variables"
echo ""

echo "=========================================="
echo "For detailed documentation, see:"
echo "- NOTIFICATION_API_DOCUMENTATION.md"
echo "- JANIDU_NOTIFICATION_MODULE_GUIDE.md"
echo "=========================================="
