package backend.enums;

public enum NotificationType {
    BOOKING_APPROVED,
    BOOKING_REJECTED,
    BOOKING_CANCELLED,
    TICKET_CREATED,
    TICKET_ASSIGNED,
    TICKET_IN_PROGRESS,
    TICKET_RESOLVED,
    TICKET_CLOSED,
    TICKET_REJECTED,
    COMMENT_ADDED,
    COMMENT_REPLIED
}
