spring.data.mongodb.uri=mongodb+srv://jmadawas_db_user:4PKMGqQtBBpViZI2@cluster0.vpkxvmi.mongodb.net/smart_campus_db?retryWrites=true&w=majority
spring.data.mongodb.auto-index-creation=true
spring.application.name=backend

server.port=8080

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true

spring.profiles.active=dev