spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=smart_campus_db
spring.data.mongodb.auto-index-creation=${MONGO_AUTO_INDEX:true}
spring.application.name=${SPRING_APP_NAME:backend}

server.port=8080

spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE:10MB}
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE:10MB}
spring.servlet.multipart.enabled=true

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Cloudinary Configuration
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

# Cleaner logs
logging.level.root=WARN
logging.level.org.springframework=INFO
logging.level.org.mongodb=ERROR